from pathlib import Path


ROOT = Path(__file__).parent


DIRECTORIES = [
    "data/raw",
    "data/processed",
    "data/interim",
    "docs/api",
    "docs/design_docs",
    "docs/tutorials",
    "docs/diagrams",
    "notebooks/eda",
    "notebooks/model_experiments",
    "notebooks/results",
    "src/data_pipeline/sourcing/downloaders",
    "src/data_pipeline/sourcing/scrapers",
    "src/data_pipeline/sourcing/validators",
    "src/data_pipeline/sourcing/annotations",
    "src/data_pipeline/preprocessing/cleaners",
    "src/data_pipeline/preprocessing/transformers",
    "src/data_pipeline/preprocessing/encoders",
    "src/data_pipeline/preprocessing/splitters",
    "src/data_pipeline/augmentations/image",
    "src/data_pipeline/augmentations/text",
    "src/data_pipeline/augmentations/audio",
    "src/data_pipeline/augmentations/utils",
    "src/data_pipeline/loaders/dataset_classes",
    "src/data_pipeline/loaders/generators",
    "src/data_pipeline/loaders/batchers",
    "src/data_pipeline/loaders/async_loaders",
    "src/data_pipeline/validation/sanity_checks",
    "src/data_pipeline/validation/statistics",
    "src/data_pipeline/validation/comparers",
    "src/data_pipeline/utils/visualization",
    "src/data_pipeline/utils/logging",
    "src/data_pipeline/utils/helpers",
    "src/models/architectures",
    "src/models/layers",
    "src/models/losses",
    "src/models/metrics",
    "src/training/experiments/experiment1/logs",
    "src/training/experiments/experiment1/results",
    "src/training/experiments/experiment2",
    "src/training/scripts",
    "src/training/hyperparameters/search_algos",
    "src/training/hyperparameters/search_spaces",
    "src/training/hyperparameters/tuning_results",
    "src/training/callbacks/lr_schedulers",
    "src/training/callbacks",
    "src/training/strategies",
    "src/training/metrics",
    "src/training/utils",
    "src/inference/deployment/docker",
    "src/inference/deployment/cloud_functions",
    "src/inference/deployment/api_endpoints",
    "src/inference/deployment/edge_devices",
    "src/inference/tools/model_converters",
    "src/inference/tools/benchmarking",
    "src/inference/tools/visualization",
    "src/inference/utils/preprocessing",
    "src/inference/utils/postprocessing",
    "src/inference/utils/logging",
    "src/testing/unit_tests/data_pipeline_tests",
    "src/testing/unit_tests/model_tests",
    "src/testing/unit_tests/training_utils_tests",
    "src/testing/integration_tests/pipeline_integration",
    "src/testing/integration_tests/model_training_integration",
    "src/testing/utils/fixtures",
    "src/testing/utils/mockers",
    "src/testing/utils/visualization",
    "src/utils/file_handlers",
    "src/utils/visualization",
    "src/utils/others",
    "results/models",
    "results/plots",
    "results/tables",
    "config",
]


FILES_WITH_PLACEHOLDERS = {
    "README.md": "# Project Overview\n\nScaffold generated by create_structure.py.\n",
    "src/training/experiments/experiment1/config.yml": "name: experiment1\nnotes: placeholder config\n",
    "src/training/scripts/train_model.py": '"""Entry point for training models."""\n\n\ndef main() -> None:\n    print("Train model script placeholder")\n\n\nif __name__ == "__main__":\n    main()\n',
    "src/training/scripts/validate_model.py": '"""Validation entry point."""\n\n\ndef main() -> None:\n    print("Validate model script placeholder")\n\n\nif __name__ == "__main__":\n    main()\n',
    "src/training/scripts/resume_training.py": '"""Resume training entry point."""\n\n\ndef main() -> None:\n    print("Resume training script placeholder")\n\n\nif __name__ == "__main__":\n    main()\n',
    "src/training/scripts/distributed_train.py": '"""Distributed training entry point."""\n\n\ndef main() -> None:\n    print("Distributed train script placeholder")\n\n\nif __name__ == "__main__":\n    main()\n',
    "src/training/hyperparameters/search_algos/grid_search.py": "# Placeholder for grid search implementation\n",
    "src/training/hyperparameters/search_algos/random_search.py": "# Placeholder for random search implementation\n",
    "src/training/hyperparameters/search_algos/bayesian_optimization.py": "# Placeholder for bayesian optimization implementation\n",
    "src/training/callbacks/early_stopping.py": "# Placeholder for early stopping callback\n",
    "src/training/callbacks/model_checkpointing.py": "# Placeholder for model checkpointing\n",
    "src/training/callbacks/tensorboard_logging.py": "# Placeholder for tensorboard logging\n",
    "src/training/strategies/single_gpu_strategy.py": "# Placeholder for single GPU strategy\n",
    "src/training/strategies/multi_gpu_strategy.py": "# Placeholder for multi GPU strategy\n",
    "src/training/strategies/tpu_strategy.py": "# Placeholder for TPU strategy\n",
    "src/training/metrics/accuracy.py": "# Placeholder for accuracy metric\n",
    "src/training/metrics/f1_score.py": "# Placeholder for F1 score metric\n",
    "src/training/metrics/custom_metric.py": "# Placeholder for custom metric\n",
    "src/training/utils/gradient_clipping.py": "# Placeholder for gradient clipping utilities\n",
    "src/training/utils/weight_initialization.py": "# Placeholder for weight initialization strategies\n",
    "src/training/utils/mixed_precision.py": "# Placeholder for mixed precision utilities\n",
    "config/environment.yml": "# Placeholder conda environment\n",
    "config/requirements.txt": "# Add Python requirements here\n",
    "config/model_config.yml": "# Add model and training configuration here\n",
}


def create_directories() -> None:
    for directory in DIRECTORIES:
        path = ROOT / directory
        path.mkdir(parents=True, exist_ok=True)


def create_files() -> None:
    for relative_path, content in FILES_WITH_PLACEHOLDERS.items():
        file_path = ROOT / relative_path
        file_path.parent.mkdir(parents=True, exist_ok=True)
        if not file_path.exists():
            file_path.write_text(content, encoding="utf-8")


def main() -> None:
    create_directories()
    create_files()
    print("Project structure created.")


if __name__ == "__main__":
    main()
